### ISSUE TITLE
pre-commit failed raise `Missing "sha" field`

### ISSUE THREAD

**Issue by rfyiamcool** [dnephin/pre-commit-golang#31]
### failed stdout:

```
An error has occurred: InvalidConfigError: Missing "sha" field for repository git://github.com/dnephin/pre-commit-golang
Check the log at ~/.pre-commit/pre-commit.log
```

cat xx.log

```
An error has occurred: InvalidConfigError: Missing "sha" field for repository git://github.com/dnephin/pre-commit-golang
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pre_commit/error_handler.py", line 47, in error_handler
    yield
  File "/Library/Python/2.7/site-packages/pre_commit/main.py", line 157, in main
    return run(runner, args)
  File "/Library/Python/2.7/site-packages/pre_commit/commands/run.py", line 195, in run
    repo_hooks = list(get_repo_hooks(runner))
  File "/Library/Python/2.7/site-packages/pre_commit/commands/run.py", line 141, in get_repo_hooks
    for repo in runner.repositories:
  File "/Library/Python/2.7/site-packages/cached_property.py", line 26, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/Library/Python/2.7/site-packages/pre_commit/runner.py", line 44, in repositories
    config = load_config(self.config_file_path)
  File "/Library/Python/2.7/site-packages/pre_commit/clientlib/validate_base.py", line 63, in validate
    additional_validation_strategy(obj)
  File "/Library/Python/2.7/site-packages/pre_commit/clientlib/validate_config.py", line 75, in validate_config_extra
    'Missing "sha" field for repository {0}'.format(repo['repo'])
InvalidConfigError: Missing "sha" field for repository git://github.com/dnephin/pre-commit-golang
```

**Comment by rfyiamcool** [comment]
reinstal  pre-commit
